export const genreAliases = [
  "|3D|",
  "|3D models on 2D backgrounds|3D on 2D|",
  "|Action|Action (Shooter)|",
  "|Adventure|Adventure. RPG|adventure|",
  "|Beat'em up|Beat 'em up (Brawler)|Beat 'em up|",
  "|Card game|CCG|",
  "|Deck Building|Deck-building|",
  "|Detective|Detective Fiction|Detective fiction|",
  "|Dungeon Crawler|Dungeon crawl|",
  "|Fantasy|fantasy|",
  "|Fighting|",
  "|First Person|First person|First person view|First-Person|First-person|First-person,3D|",
  "|Golf|Golf. 3D|",
  "|Hack'n Slash|Hack n'Slash|Hack'n slash|",
  "|Horror|Horror,Japanese|",
  "|Interactive fiction|Interactive movie|",
  "|Isometric|Isometry|Istometric|",
  "|Japanese|",
  "|Logic|Logical|",
  "|Management|Managerial|",
  "|Medieval|Middle Ages|",
  "|Open World|Open world|Open-World|Open-world|",
  "|Party-Based|Party-based|",
  "|Pausable Real-time|Pausable real-time|Active time battle|",
  "|Platform Adventure|Platform adventure|",
  "|Point & Click|Point and Click|Point-and-Click|Point-and-click|",
  "|Post-Apocalyptic|Post-apocalypse|Post-apocalypstic|Post-apocalyptic|",
  "|Psychological|psychological|",
  "|Puzzle|Puzzle Solving|Puzzle solving|Puzzle-Solving|Puzzle-like|Puzzle-solving|",
  "|RPG|Adventure. RPG|",
  "|Real-Time|Real-time|",
  "|Retro|Retro look|",
  "|Rhythm|Rhythm game|",
  "|Roguelike|Rogue-like|",
  "|Shoot 'em Up|Shoot 'em up|Shoot 'em upm Isometric|Shoot'Em-Up|Shoot-‘Em-Up|",
  "|Shooter|Action (Shooter)|",
  "|Side|Side view|",
  "|Simulation|Simulator (Space)|",
  "|Space|Simulator (Space)|",
  "|Third Person|Third person|Third person view|Third-Person|Third-person|Third-person,3D|Third-person. 3D|",
  "|Tile-matching|Tile-matching (Match-3)|",
  "|Top view|Top-Down|Top-down|",
  "|Tower Defense|Tower defense|",
  "|Turn-Based|Turn-based|",
  "|Vehicular Combat|Vehicular combat|",
  "|Visual Novel|Visual novel|",
  "|Zombie|Zombies|",
]
